name: Deploy-firstVM

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
permissions:
  id-token: write
  contents: read

env:
    AZURE_RESOURCEGROUP_NAME: project4
    adminUsername: elgonusername
    adminPassword: OurPmmmw0rd1998
    securityType: Standard
    VmName: VM-E
    vmSize: Standard_D2s_v5
    

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Bicep linter
      run: az bicep build --file deploy/main.bicep
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/arm-deploy@v1
      name: Run preflight validation
      with:
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./deploy/main.bicep
        deploymentMode: Validate
        parameters:
          adminUsername=${{ env.adminUsername }}
          adminPassword=${{ env.adminPassword }}
          securityType=${{env.securityType}}
          vmName=${{env.VmName}}
          vmSize=${{env.vmSize}}
 
  deploy:
    runs-on: ubuntu-latest
    needs: [lint, validate]
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.run_number }}
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./deploy/main.bicep
        parameters:
          adminUsername=${{ env.adminUsername }}
          adminPassword=${{ env.adminPassword }}
          securityType=${{env.securityType}}
          vmName=${{env.VmName}}
          vmSize=${{env.vmSize}}