name: Deploy-firstVM

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
permissions:
  id-token: write
  contents: read

env:
    AZURE_RESOURCEGROUP_NAME: project4
    adminUsername: elgonusername
    adminPassword: OurPmmmw0rd1998
    securityType: Standard
    VmName: VM-E
    vmSize: Standard_D2s_v5
    

jobs:

  preview:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/arm-deploy@v1
      name: Run what-if
      with:
        failOnStdErr: false
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: deploy/main.bicep
        parameters: >
          environmentType=${{ env.ENVIRONMENT_TYPE }}
        additionalArguments: --what-if

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.run_number }}
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./deploy/main.bicep
        parameters:
          adminUsername=${{ env.adminUsername }}
          adminPassword=${{ env.adminPassword }}
          securityType=${{env.securityType}}
          vmName=${{env.VmName}}
          vmSize=${{env.vmSize}}